### PR TITLE
Fix condition where inertia_share data gets erased for forever on second request

### LINKED ISSUE #15: inertia_share fails on second request
I'm playing around with `inertia_rails` within a Rails 6 application like this:

```ruby
class ApplicationController < ActionController::Base
  inertia_share do
    {
      foo: 42
    }
  end
end
```

This works fine on the first request (props include `foo:42`), but all subsequent requests fail (props not include `foo:42`). When I modify my source file (`application_controller.rb`) and change `foo` to 43, it works on the following one request, but the next requests will fail again.

This can be reproduced with the test suite when you swap the order of the two context blocks in this file: https://github.com/inertiajs/inertia-rails/blob/a27564bb512e6bdb28517e8b2b4de39419a57371/spec/inertia/sharing_spec.rb#L4-L18

Seems to be caused by #13.

### PR DESCRIPTION
**Pull request by bknoles**
Closes #15 

As @ledermann points out in #15 and PR #17 , the calls to `inertia_share` from a controller only run the first time the class is loaded and the data is subsequently deleted forever on the next request, because of the `InertiaRails.reset!` call in the middleware... presumably, we didn't notice this in development either due to classes reloading when changed, or maybe because `config.cache_classes = false` in development environments.

The PR does a lot of refactoring that we want to discuss before merging in, so I created this PR, which solves the bug without changing much code.

The basic idea is to wrap the `InertiaRails.share` calls inside a block given to `before_action`. This, combined with the current `InertiaRails.reset!` call in the middleware, ensures that shared data is recalculated from scratch on each request.

I wrote a test to check inheritance as well, which seems to work as well, though this change isn't explicitly intended to add support for inheritance.

### CODE REVIEW

File: lib/inertia_rails/controller.rb [hunk 1]
```diff
@@ -6,8 +6,10 @@ module Controller
 
     module ClassMethods
       def inertia_share(**args, &block)
-        InertiaRails.share(args) if args
-        InertiaRails.share_block(block) if block
+        before_action do
```
Comment (bknoles) [inline lib/inertia_rails/controller.rb]: because we clear data in the middleware, we need to re-share the data on each request

File: spec/inertia/sharing_spec.rb [hunk 2]
```diff
@@ -1,19 +1,40 @@
...
+
+    before do
+      get share_path, headers: {'X-Inertia' => true}
+      get share_path, headers: {'X-Inertia' => true}
+    end
+
+    it { is_expected.to eq props }
+  end
+
+  context 'using inertia share with inheritance' do
```
Comment (bknoles) [inline spec/inertia/sharing_spec.rb]: this seems to work with inherited controllers, though there may be some other cases which behave differently

**Comment by ledermann** [comment]
Adding and deleting the shared data on every single request doesn't seem right to me. But ok, this fixes the issue with minimal code changes :-)

**Comment by ledermann** [comment]
Any news here? Without merging a patch (either this PR or #17) the gem is broken.

**Comment by BrandonShar** [comment]
Thanks for the bump @ledermann ! It's been a busy week for us.

**Comment by bknoles** [comment]
yes, my apologies... last week was a holiday here and cutting the new gem version fell off my todo list! thanks for picking it up brandon!
